%%%%%%%%%%%%%%%%%%%%
%% Generated by ViRAGe 0.1.0 at 2023-09-26 04:35:52 MESZ.
%%%%%%%%%%%%%%%%%%%%
%% To add new composition rules, go to the bottom of this file.
%% A rule definition consists of three parts. The first one represents its origin,
%% for user defined rules this will always be "UNPROVEN". The second part is
%% the symbolic name of the rule that will be used in generated proofs.
%% The third part is a Prolog clause capturing the semantics of the rule.
%%
%% Example:
%% % = UNPROVEN
%% % example_rule_without_meaning
%% property_a(X) :- property_b(X).
%%%%%%%%%%%%%%%%%%%%
% ==== src/test/resources/verifiedVotingRuleConstruction/theories/ROOT - Verified_Voting_Rule_Construction
%
% === COMPONENT_TYPE
% == Rel.rel(?'a)
% == Set.set(?'a)
% elimination_set(Evaluation_Function,Nat.nat,Nat.nat,Nat.nat,HOL.bool,Set.set(?'a),Profile)
% == HOL.bool
% == Electoral_Module
% iterelect(Electoral_Module)
% pairwise_majority_rule'()
% loop_comp_helper(Electoral_Module,Electoral_Module,Termination_Condition)
% pass_module(Nat.nat,Preference_Relation)
% schwartz_rule()
% drop_module(Nat.nat,Preference_Relation)
% sequential_composition(Electoral_Module,Electoral_Module)
% elimination_module(Evaluation_Function,Nat.nat,Nat.nat,Nat.nat,HOL.bool)
% borda_rule()
% borda()
% copeland_rule()
% pairwise_majority_rule()
% loop_composition(Electoral_Module,Termination_Condition)
% plurality()
% leq_eliminator(Evaluation_Function,Nat.nat)
% less_average_eliminator(Evaluation_Function)
% leq_average_eliminator(Evaluation_Function)
% condorcet()
% elect_module()
% max_eliminator(Evaluation_Function)
% maximum_parallel_composition(Electoral_Module,Electoral_Module)
% iter(Electoral_Module)
% parallel_composition(Electoral_Module,Electoral_Module,Aggregator)
% minimax_rule()
% elector(Electoral_Module)
% defer_module()
% minimax()
% less_eliminator(Evaluation_Function,Nat.nat)
% revision_composition(Electoral_Module)
% blacks_rule()
% classic_nanson_rule()
% smc(Preference_Relation)
% min_eliminator(Evaluation_Function)
% condorcet'()
% nanson_baldwin_rule()
% copeland()
% == Nat.nat
% average(Evaluation_Function,Set.set(?'a),Profile)
% win_count_code(Profile,?'a)
% prefer_count(Profile,?'a,?'a)
% rank(Preference_Relation,?'a)
% prefer_count_code(Profile,?'a,?'a)
% win_count(Profile,?'a)
% == Termination_Condition
% defer_equal_condition(Nat.nat)
% set_equals_partition(Set.set(?'a))
% well_formed(Set.set(?'a))
% disjoint3()
% == Aggregator
% max_aggregator()
% == ?'a
% == List.list(?'a)
% times(Nat.nat,List.list(?'a))
% == Preference_Relation
% limit(Set.set(?'a),Preference_Relation)
% == Profile
% limit_profile(Set.set(?'a),Profile)
% == Evaluation_Function
% copeland_score()
% condorcet_score()
% minimax_score()
% borda_score()
%
% === PROPERTY
% defer_condorcet_consistency(Electoral_Module)
% wins(?'a,Profile,?'a)
% is_less_preferred_than(?'a,Preference_Relation,?'a)
% aggregator(Aggregator)
% linear_order(Preference_Relation)
% condorcet_compatibility(Electoral_Module)
% defer_invariant_monotonicity(Electoral_Module)
% indep_of_alt(Electoral_Module,Set.set(?'a),?'a)
% prof_contains_result(Electoral_Module,Set.set(?'a),Profile,Profile,?'a)
% non_blocking(Electoral_Module)
% defer_deciding(Electoral_Module)
% agg_commutative(Aggregator)
% rejects(Nat.nat,Electoral_Module)
% condorcet_rating(Evaluation_Function)
% invariant_monotonicity(Electoral_Module)
% agg_conservative(Aggregator)
% trans(Preference_Relation)
% electoral_module(Electoral_Module)
% connex(Set.set(?'a),Preference_Relation)
% defers(Nat.nat,Electoral_Module)
% lifted(Set.set(?'a),Preference_Relation,Preference_Relation,?'a)
% limited(Set.set(?'a),Preference_Relation)
% profile(Set.set(?'a),Profile)
% electing(Electoral_Module)
% non_electing(Electoral_Module)
% defer_lift_invariance(Electoral_Module)
% monotonicity(Electoral_Module)
% prof_geq_result(Electoral_Module,Set.set(?'a),Profile,Profile,?'a)
% custom_greater(Nat.nat,Nat.nat)
% equiv_prof_except_a(Set.set(?'a),Profile,Profile,?'a)
% homogeneity(Electoral_Module)
% prof_leq_result(Electoral_Module,Set.set(?'a),Profile,Profile,?'a)
% mod_contains_result(Electoral_Module,Electoral_Module,Set.set(?'a),Profile,?'a)
% eliminates(Nat.nat,Electoral_Module)
% defer_monotonicity(Electoral_Module)
% decrementing(Electoral_Module)
% disjoint_compatibility(Electoral_Module,Electoral_Module)
% elects(Nat.nat,Electoral_Module)
% condorcet_consistency(Electoral_Module)
% finite_profile(Set.set(?'a),Profile)
% equiv_rel_except_a(Set.set(?'a),Preference_Relation,Preference_Relation,?'a)
% condorcet_winner(Set.set(?'a),Profile,?'a)
% linear_order(Preference_Relation)
% trans(Preference_Relation)
% finite_profile(Set.set(?'a),Profile)
% custom_greater(Nat.nat,Nat.nat)
%
% === COMPOSITION_RULE
% = Aggregator_Facts.thy
% Aggregator_Facts.max_agg_comm
agg_commutative(max_aggregator).

% = Aggregator_Facts.thy
% Aggregator_Facts.max_agg_consv
agg_conservative(max_aggregator).

% = Maximum_Aggregator.thy
% Maximum_Aggregator.max_agg_sound
aggregator(max_aggregator).

% = Preference_Relation.thy
% Preference_Relation.lin_imp_antisym
antisym(R) :- linear_order_on(_,R).

% = ASSUMPTION
% condorcet_compatibility_alias_0
condorcet_compatibility(iter(X)) :- condorcet_compatibility(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% condorcet_compatibility_alias_1
condorcet_compatibility(iterelect(X)) :- condorcet_compatibility(elector(iter(X))).

% = ASSUMPTION
% condorcet_compatibility_alias_2
condorcet_compatibility(maximum_parallel_composition(X,Y)) :- condorcet_compatibility(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% condorcet_compatibility_alias_3
condorcet_compatibility(smc(X)) :- condorcet_compatibility(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% condorcet_compatibility_alias_4
condorcet_compatibility(elector(X)) :- condorcet_compatibility(sequential_composition(X,elect_module)).

% = Condorcet_Rules.thy
% Condorcet_Rules.cr_eval_imp_ccomp_max_elim
condorcet_compatibility(max_eliminator(E)) :- finite_profile(_,_),condorcet_rating(E).

% = Pairwise_Majority_Rule.thy
% Pairwise_Majority_Rule.condorcet_condorcet
condorcet_consistency(pairwise_majority_rule).

% = Minimax_Rule.thy
% Minimax_Rule.minimax_condorcet
condorcet_consistency(minimax_rule).

% = Copeland_Rule.thy
% Copeland_Rule.copeland_condorcet
condorcet_consistency(copeland_rule).

% = Condorcet_Rules.thy
% Condorcet_Rules.dcc_imp_cc_elector
condorcet_consistency(elector(M)) :- defer_condorcet_consistency(M).

% = ASSUMPTION
% condorcet_consistency_alias_0
condorcet_consistency(iter(X)) :- condorcet_consistency(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% condorcet_consistency_alias_1
condorcet_consistency(iterelect(X)) :- condorcet_consistency(elector(iter(X))).

% = ASSUMPTION
% condorcet_consistency_alias_2
condorcet_consistency(maximum_parallel_composition(X,Y)) :- condorcet_consistency(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% condorcet_consistency_alias_3
condorcet_consistency(smc(X)) :- condorcet_consistency(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% condorcet_consistency_alias_4
condorcet_consistency(elector(X)) :- condorcet_consistency(sequential_composition(X,elect_module)).

% = Condorcet_Facts.thy
% Condorcet_Facts.minimax_score_cond_rating
condorcet_rating(minimax_score).

% = Condorcet_Facts.thy
% Condorcet_Facts.condorcet_score_is_condorcet_rating
condorcet_rating(condorcet_score).

% = Condorcet_Facts.thy
% Condorcet_Facts.copeland_score_is_cr
condorcet_rating(copeland_score).

% = ASSUMPTION
% condorcet_winner_intro
condorcet_winner(_,_,_).

% = ASSUMPTION
% connex_intro
connex(_,_).

% = Preference_Relation.thy
% Preference_Relation.lin_ord_imp_connex
connex(A,R) :- linear_order_on(A,R).

% = ASSUMPTION
% decrementing_alias_0
decrementing(iter(X)) :- decrementing(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% decrementing_alias_1
decrementing(iterelect(X)) :- decrementing(elector(iter(X))).

% = ASSUMPTION
% decrementing_alias_2
decrementing(maximum_parallel_composition(X,Y)) :- decrementing(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% decrementing_alias_3
decrementing(smc(X)) :- decrementing(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% decrementing_alias_4
decrementing(elector(X)) :- decrementing(sequential_composition(X,elect_module)).

% = Condorcet_Facts.thy
% Condorcet_Facts.copeland_is_dcc
defer_condorcet_consistency(copeland).

% = Condorcet_Facts.thy
% Condorcet_Facts.condorcet_is_dcc
defer_condorcet_consistency(condorcet).

% = Condorcet_Facts.thy
% Condorcet_Facts.minimax_is_dcc
defer_condorcet_consistency(minimax).

% = Condorcet_Rules.thy
% Condorcet_Rules.cr_eval_imp_dcc_max_elim
defer_condorcet_consistency(max_eliminator(E)) :- condorcet_rating(E).

% = ASSUMPTION
% defer_condorcet_consistency_alias_0
defer_condorcet_consistency(iter(X)) :- defer_condorcet_consistency(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% defer_condorcet_consistency_alias_1
defer_condorcet_consistency(iterelect(X)) :- defer_condorcet_consistency(elector(iter(X))).

% = ASSUMPTION
% defer_condorcet_consistency_alias_2
defer_condorcet_consistency(maximum_parallel_composition(X,Y)) :- defer_condorcet_consistency(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% defer_condorcet_consistency_alias_3
defer_condorcet_consistency(smc(X)) :- defer_condorcet_consistency(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% defer_condorcet_consistency_alias_4
defer_condorcet_consistency(elector(X)) :- defer_condorcet_consistency(sequential_composition(X,elect_module)).

% = Condorcet_Rules.thy
% Condorcet_Rules.ccomp_and_dd_imp_dcc
defer_condorcet_consistency(M) :- condorcet_compatibility(M),defer_deciding(M).

% = ASSUMPTION
% defer_deciding_alias_0
defer_deciding(iter(X)) :- defer_deciding(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% defer_deciding_alias_1
defer_deciding(iterelect(X)) :- defer_deciding(elector(iter(X))).

% = ASSUMPTION
% defer_deciding_alias_2
defer_deciding(maximum_parallel_composition(X,Y)) :- defer_deciding(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% defer_deciding_alias_3
defer_deciding(smc(X)) :- defer_deciding(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% defer_deciding_alias_4
defer_deciding(elector(X)) :- defer_deciding(sequential_composition(X,elect_module)).

% = Monotonicity_Rules.thy
% Monotonicity_Rules.rev_comp_def_inv_mono
defer_invariant_monotonicity(revision_composition(M)) :- invariant_monotonicity(M).

% = ASSUMPTION
% defer_invariant_monotonicity_alias_0
defer_invariant_monotonicity(iter(X)) :- defer_invariant_monotonicity(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% defer_invariant_monotonicity_alias_1
defer_invariant_monotonicity(iterelect(X)) :- defer_invariant_monotonicity(elector(iter(X))).

% = ASSUMPTION
% defer_invariant_monotonicity_alias_2
defer_invariant_monotonicity(maximum_parallel_composition(X,Y)) :- defer_invariant_monotonicity(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% defer_invariant_monotonicity_alias_3
defer_invariant_monotonicity(smc(X)) :- defer_invariant_monotonicity(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% defer_invariant_monotonicity_alias_4
defer_invariant_monotonicity(elector(X)) :- defer_invariant_monotonicity(sequential_composition(X,elect_module)).

% = Monotonicity_Facts.thy
% Monotonicity_Facts.def_mod_def_lift_inv
defer_lift_invariance(defer_module).

% = Monotonicity_Rules.thy
% Monotonicity_Rules.loop_comp_presv_def_lift_inv
defer_lift_invariance(loop_composition(M,_)) :- defer_lift_invariance(M).

% = Monotonicity_Facts.thy
% Monotonicity_Facts.pass_mod_dl_inv
defer_lift_invariance(pass_module(_,R)) :- linear_order(R).

% = Monotonicity_Facts.thy
% Monotonicity_Facts.drop_mod_def_lift_inv
defer_lift_invariance(drop_module(_,R)) :- linear_order(R).

% = ASSUMPTION
% defer_lift_invariance_alias_0
defer_lift_invariance(iter(X)) :- defer_lift_invariance(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% defer_lift_invariance_alias_1
defer_lift_invariance(iterelect(X)) :- defer_lift_invariance(elector(iter(X))).

% = ASSUMPTION
% defer_lift_invariance_alias_2
defer_lift_invariance(maximum_parallel_composition(X,Y)) :- defer_lift_invariance(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% defer_lift_invariance_alias_3
defer_lift_invariance(smc(X)) :- defer_lift_invariance(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% defer_lift_invariance_alias_4
defer_lift_invariance(elector(X)) :- defer_lift_invariance(sequential_composition(X,elect_module)).

% = Monotonicity_Rules.thy
% Monotonicity_Rules.seq_comp_presv_def_lift_inv
defer_lift_invariance(sequential_composition(M,N)) :- defer_lift_invariance(M),defer_lift_invariance(N).

% = Monotonicity_Rules.thy
% Monotonicity_Rules.loop_comp_helper_presv_def_lift_inv
defer_lift_invariance(loop_comp_helper(ACC,M,_)) :- defer_lift_invariance(M),defer_lift_invariance(ACC).

% = Monotonicity_Rules.thy
% Monotonicity_Rules.par_comp_def_lift_inv
defer_lift_invariance(maximum_parallel_composition(M,N)) :- disjoint_compatibility(M,N),defer_lift_invariance(M),defer_lift_invariance(N).

% = Monotonicity_Rules.thy
% Monotonicity_Rules.def_inv_mono_imp_def_lift_inv
defer_lift_invariance(sequential_composition(M,N)) :- defer_invariant_monotonicity(M),non_electing(N),defers(1,N),defer_monotonicity(N).

% = Monotonicity_Rules.thy
% Monotonicity_Rules.dl_inv_imp_def_mono
defer_monotonicity(M) :- defer_lift_invariance(M).

% = ASSUMPTION
% defer_monotonicity_alias_0
defer_monotonicity(iter(X)) :- defer_monotonicity(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% defer_monotonicity_alias_1
defer_monotonicity(iterelect(X)) :- defer_monotonicity(elector(iter(X))).

% = ASSUMPTION
% defer_monotonicity_alias_2
defer_monotonicity(maximum_parallel_composition(X,Y)) :- defer_monotonicity(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% defer_monotonicity_alias_3
defer_monotonicity(smc(X)) :- defer_monotonicity(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% defer_monotonicity_alias_4
defer_monotonicity(elector(X)) :- defer_monotonicity(sequential_composition(X,elect_module)).

% = Result_Facts.thy
% Result_Facts.pass_zero_mod_def_zero
defers(0,pass_module(0,R)) :- linear_order(R).

% = Result_Facts.thy
% Result_Facts.pass_one_mod_def_one
defers(1,pass_module(1,R)) :- linear_order(R).

% = Result_Facts.thy
% Result_Facts.pass_two_mod_def_two
defers(2,pass_module(2,R)) :- linear_order(R).

% = ASSUMPTION
% defers_alias_0
defers(ALIAS_VAR_0,iter(X)) :- defers(ALIAS_VAR_0,loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% defers_alias_1
defers(ALIAS_VAR_0,iterelect(X)) :- defers(ALIAS_VAR_0,elector(iter(X))).

% = ASSUMPTION
% defers_alias_2
defers(ALIAS_VAR_0,maximum_parallel_composition(X,Y)) :- defers(ALIAS_VAR_0,parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% defers_alias_3
defers(ALIAS_VAR_0,smc(X)) :- defers(ALIAS_VAR_0,iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% defers_alias_4
defers(ALIAS_VAR_0,elector(X)) :- defers(ALIAS_VAR_0,sequential_composition(X,elect_module)).

% = Result_Rules.thy
% Result_Rules.seq_comp_def_one
defers(1,sequential_composition(M,N)) :- non_blocking(M),non_electing(M),defers(1,N).

% = Sequential_Composition.thy
% Sequential_Composition.seq_comp_presv_disj
disjoint3(sequential_composition(M,N,A,P)) :- electoral_module(M),electoral_module(N),finite_profile(A,P).

% = Disjoint_Compatibility_Facts.thy
% Disjoint_Compatibility_Facts.drop_pass_disj_compat
disjoint_compatibility(drop_module(N,R),pass_module(N,R)) :- linear_order(R).

% = Disjoint_Compatibility_Rules.thy
% Disjoint_Compatibility_Rules.disj_compat_comm
disjoint_compatibility(N,M) :- disjoint_compatibility(M,N).

% = ASSUMPTION
% disjoint_compatibility_alias_0
disjoint_compatibility(iter(X),ALIAS_VAR_1) :- disjoint_compatibility(loop_composition(X,defer_equal_condition(1)),ALIAS_VAR_1).

% = ASSUMPTION
% disjoint_compatibility_alias_1
disjoint_compatibility(iterelect(X),ALIAS_VAR_1) :- disjoint_compatibility(elector(iter(X)),ALIAS_VAR_1).

% = ASSUMPTION
% disjoint_compatibility_alias_2
disjoint_compatibility(maximum_parallel_composition(X,Y),ALIAS_VAR_1) :- disjoint_compatibility(parallel_composition(X,Y,max_aggregator),ALIAS_VAR_1).

% = ASSUMPTION
% disjoint_compatibility_alias_3
disjoint_compatibility(smc(X),ALIAS_VAR_1) :- disjoint_compatibility(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X))),ALIAS_VAR_1).

% = ASSUMPTION
% disjoint_compatibility_alias_4
disjoint_compatibility(elector(X),ALIAS_VAR_1) :- disjoint_compatibility(sequential_composition(X,elect_module),ALIAS_VAR_1).

% = ASSUMPTION
% disjoint_compatibility_alias_0
disjoint_compatibility(ALIAS_VAR_0,iter(X)) :- disjoint_compatibility(ALIAS_VAR_0,loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% disjoint_compatibility_alias_1
disjoint_compatibility(ALIAS_VAR_0,iterelect(X)) :- disjoint_compatibility(ALIAS_VAR_0,elector(iter(X))).

% = ASSUMPTION
% disjoint_compatibility_alias_2
disjoint_compatibility(ALIAS_VAR_0,maximum_parallel_composition(X,Y)) :- disjoint_compatibility(ALIAS_VAR_0,parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% disjoint_compatibility_alias_3
disjoint_compatibility(ALIAS_VAR_0,smc(X)) :- disjoint_compatibility(ALIAS_VAR_0,iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% disjoint_compatibility_alias_4
disjoint_compatibility(ALIAS_VAR_0,elector(X)) :- disjoint_compatibility(ALIAS_VAR_0,sequential_composition(X,elect_module)).

% = Result_Facts.thy
% Result_Facts.plurality_electing
electing(plurality).

% = Result_Facts.thy
% Result_Facts.elect_mod_electing
electing(elect_module).

% = Sequential_Majority_Comparison.thy
% Sequential_Majority_Comparison.smc_electing
electing(smc(X)) :- linear_order(X).

% = ASSUMPTION
% electing_alias_0
electing(iter(X)) :- electing(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% electing_alias_1
electing(iterelect(X)) :- electing(elector(iter(X))).

% = ASSUMPTION
% electing_alias_2
electing(maximum_parallel_composition(X,Y)) :- electing(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% electing_alias_3
electing(smc(X)) :- electing(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% electing_alias_4
electing(elector(X)) :- electing(sequential_composition(X,elect_module)).

% = Result_Rules.thy
% Result_Rules.elector_electing
electing(elector(M)) :- electoral_module(M),non_blocking(M).

% = Result_Rules.thy
% Result_Rules.seq_comp_electing
electing(sequential_composition(M10,M20)) :- defers(1,M10),electing(M20).

% = Defer_Module.thy
% Defer_Module.def_mod_sound
electoral_module(defer_module).

% = Elect_Module.thy
% Elect_Module.elect_mod_sound
electoral_module(elect_module).

% = Elimination_Module.thy
% Elimination_Module.less_elim_sound
electoral_module(less_eliminator(_,_)).

% = Elimination_Module.thy
% Elimination_Module.leq_elim_sound
electoral_module(leq_eliminator(_,_)).

% = Elimination_Module.thy
% Elimination_Module.leq_avg_elim_sound
electoral_module(leq_average_eliminator(_)).

% = Elimination_Module.thy
% Elimination_Module.elim_mod_sound
electoral_module(elimination_module(_,_,_)).

% = Elimination_Module.thy
% Elimination_Module.max_elim_sound
electoral_module(max_eliminator(_)).

% = Elimination_Module.thy
% Elimination_Module.min_elim_sound
electoral_module(min_eliminator(_)).

% = Elimination_Module.thy
% Elimination_Module.less_avg_elim_sound
electoral_module(less_average_eliminator(_)).

% = Plurality_Module.thy
% Plurality_Module.plurality_sound
electoral_module(plurality).

% = Composite_Structures.thy
% Composite_Structures.elector_sound
electoral_module(elector(M)) :- electoral_module(M).

% = Loop_Composition.thy
% Loop_Composition.loop_comp_sound
electoral_module(loop_composition(M,_)) :- electoral_module(M).

% = Drop_Module.thy
% Drop_Module.drop_mod_sound
electoral_module(drop_module(_,R)) :- linear_order(R).

% = Pass_Module.thy
% Pass_Module.pass_mod_sound
electoral_module(pass_module(_,R)) :- linear_order(R).

% = Sequential_Majority_Comparison.thy
% Sequential_Majority_Comparison.smc_sound
electoral_module(smc(X)) :- linear_order(X).

% = Revision_Composition.thy
% Revision_Composition.rev_comp_sound
electoral_module(revision_composition(M)) :- electoral_module(M).

% = ASSUMPTION
% electoral_module_alias_0
electoral_module(iter(X)) :- electoral_module(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% electoral_module_alias_1
electoral_module(iterelect(X)) :- electoral_module(elector(iter(X))).

% = ASSUMPTION
% electoral_module_alias_2
electoral_module(maximum_parallel_composition(X,Y)) :- electoral_module(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% electoral_module_alias_3
electoral_module(smc(X)) :- electoral_module(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% electoral_module_alias_4
electoral_module(elector(X)) :- electoral_module(sequential_composition(X,elect_module)).

% = Composite_Structures.thy
% Composite_Structures.max_par_comp_sound
electoral_module(maximum_parallel_composition(M,N)) :- electoral_module(M),electoral_module(N).

% = Sequential_Composition.thy
% Sequential_Composition.seq_comp_sound
electoral_module(sequential_composition(M,N)) :- electoral_module(M),electoral_module(N).

% = Parallel_Composition.thy
% Parallel_Composition.par_comp_sound
electoral_module(parallel_composition(M,N,A)) :- electoral_module(M),electoral_module(N),aggregator(A).

% = ASSUMPTION
% elects_alias_0
elects(ALIAS_VAR_0,iter(X)) :- elects(ALIAS_VAR_0,loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% elects_alias_1
elects(ALIAS_VAR_0,iterelect(X)) :- elects(ALIAS_VAR_0,elector(iter(X))).

% = ASSUMPTION
% elects_alias_2
elects(ALIAS_VAR_0,maximum_parallel_composition(X,Y)) :- elects(ALIAS_VAR_0,parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% elects_alias_3
elects(ALIAS_VAR_0,smc(X)) :- elects(ALIAS_VAR_0,iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% elects_alias_4
elects(ALIAS_VAR_0,elector(X)) :- elects(ALIAS_VAR_0,sequential_composition(X,elect_module)).

% = ASSUMPTION
% eliminates_alias_0
eliminates(ALIAS_VAR_0,iter(X)) :- eliminates(ALIAS_VAR_0,loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% eliminates_alias_1
eliminates(ALIAS_VAR_0,iterelect(X)) :- eliminates(ALIAS_VAR_0,elector(iter(X))).

% = ASSUMPTION
% eliminates_alias_2
eliminates(ALIAS_VAR_0,maximum_parallel_composition(X,Y)) :- eliminates(ALIAS_VAR_0,parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% eliminates_alias_3
eliminates(ALIAS_VAR_0,smc(X)) :- eliminates(ALIAS_VAR_0,iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% eliminates_alias_4
eliminates(ALIAS_VAR_0,elector(X)) :- eliminates(ALIAS_VAR_0,sequential_composition(X,elect_module)).

% = Result_Rules.thy
% Result_Rules.par_comp_elim_one
eliminates(1,maximum_parallel_composition(M,N)) :- defers(1,M),non_electing(M),rejects(2,N),disjoint_compatibility(M,N).

% = ASSUMPTION
% equiv_prof_except_a_intro
equiv_prof_except_a(_,_,_,_).

% = Profile.thy
% Profile.lifted_imp_equiv_prof_except_a
equiv_prof_except_a(A,P,Q,A) :- lifted(A,P,Q,A).

% = ASSUMPTION
% equiv_rel_except_a_intro
equiv_rel_except_a(_,_,_,_).

% = Preference_Relation.thy
% Preference_Relation.lifted_imp_equiv_rel_except_a
equiv_rel_except_a(A,R,S,A) :- lifted(A,R,S,A).

% = ASSUMPTION
% finite_profile_intro
finite_profile(_,_).

% = Monotonicity_Rules.thy
% Monotonicity_Rules.lifted_imp_fin_prof
finite_profile(A,P) :- lifted(A,P,_,A).

% = ASSUMPTION
% homogeneity_alias_0
homogeneity(iter(X)) :- homogeneity(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% homogeneity_alias_1
homogeneity(iterelect(X)) :- homogeneity(elector(iter(X))).

% = ASSUMPTION
% homogeneity_alias_2
homogeneity(maximum_parallel_composition(X,Y)) :- homogeneity(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% homogeneity_alias_3
homogeneity(smc(X)) :- homogeneity(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% homogeneity_alias_4
homogeneity(elector(X)) :- homogeneity(sequential_composition(X,elect_module)).

% = ASSUMPTION
% indep_of_alt_alias_0
indep_of_alt(iter(X),ALIAS_VAR_1,ALIAS_VAR_2) :- indep_of_alt(loop_composition(X,defer_equal_condition(1)),ALIAS_VAR_1,ALIAS_VAR_2).

% = ASSUMPTION
% indep_of_alt_alias_1
indep_of_alt(iterelect(X),ALIAS_VAR_1,ALIAS_VAR_2) :- indep_of_alt(elector(iter(X)),ALIAS_VAR_1,ALIAS_VAR_2).

% = ASSUMPTION
% indep_of_alt_alias_2
indep_of_alt(maximum_parallel_composition(X,Y),ALIAS_VAR_1,ALIAS_VAR_2) :- indep_of_alt(parallel_composition(X,Y,max_aggregator),ALIAS_VAR_1,ALIAS_VAR_2).

% = ASSUMPTION
% indep_of_alt_alias_3
indep_of_alt(smc(X),ALIAS_VAR_1,ALIAS_VAR_2) :- indep_of_alt(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X))),ALIAS_VAR_1,ALIAS_VAR_2).

% = ASSUMPTION
% indep_of_alt_alias_4
indep_of_alt(elector(X),ALIAS_VAR_1,ALIAS_VAR_2) :- indep_of_alt(sequential_composition(X,elect_module),ALIAS_VAR_1,ALIAS_VAR_2).

% = Monotonicity_Facts.thy
% Monotonicity_Facts.plurality_inv_mono
invariant_monotonicity(plurality).

% = ASSUMPTION
% invariant_monotonicity_alias_0
invariant_monotonicity(iter(X)) :- invariant_monotonicity(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% invariant_monotonicity_alias_1
invariant_monotonicity(iterelect(X)) :- invariant_monotonicity(elector(iter(X))).

% = ASSUMPTION
% invariant_monotonicity_alias_2
invariant_monotonicity(maximum_parallel_composition(X,Y)) :- invariant_monotonicity(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% invariant_monotonicity_alias_3
invariant_monotonicity(smc(X)) :- invariant_monotonicity(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% invariant_monotonicity_alias_4
invariant_monotonicity(elector(X)) :- invariant_monotonicity(sequential_composition(X,elect_module)).

% = ASSUMPTION
% is_less_preferred_than_intro
is_less_preferred_than(_,_,_).

% = Preference_Relation.thy
% Preference_Relation.lifted_mono2
is_less_preferred_than(X,S,A) :- lifted(A,R,S,A),is_less_preferred_than(X,R,A).

% = ASSUMPTION
% lifted_intro
lifted(_,_,_,_).

% = Preference_Relation.thy
% Preference_Relation.limit_to_limits
limited(A,limit(A,_)).

% = ASSUMPTION
% limited_intro
limited(_,_).

% = ASSUMPTION
% linear_order_intro
linear_order(_).

% = Preference_Relation.thy
% Preference_Relation.connex_antsym_and_trans_imp_lin_ord
linear_order_on(A,R) :- connex(A,R),antisym(R),trans(R).

% = Electoral_Module.thy
% Electoral_Module.mod_contains_result_comm
mod_contains_result(N,M,A,P,A) :- mod_contains_result(M,N,A,P,A).

% = ASSUMPTION
% mod_contains_result_alias_0
mod_contains_result(iter(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- mod_contains_result(loop_composition(X,defer_equal_condition(1)),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% mod_contains_result_alias_1
mod_contains_result(iterelect(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- mod_contains_result(elector(iter(X)),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% mod_contains_result_alias_2
mod_contains_result(maximum_parallel_composition(X,Y),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- mod_contains_result(parallel_composition(X,Y,max_aggregator),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% mod_contains_result_alias_3
mod_contains_result(smc(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- mod_contains_result(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X))),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% mod_contains_result_alias_4
mod_contains_result(elector(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- mod_contains_result(sequential_composition(X,elect_module),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% mod_contains_result_alias_0
mod_contains_result(ALIAS_VAR_0,iter(X),ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- mod_contains_result(ALIAS_VAR_0,loop_composition(X,defer_equal_condition(1)),ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% mod_contains_result_alias_1
mod_contains_result(ALIAS_VAR_0,iterelect(X),ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- mod_contains_result(ALIAS_VAR_0,elector(iter(X)),ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% mod_contains_result_alias_2
mod_contains_result(ALIAS_VAR_0,maximum_parallel_composition(X,Y),ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- mod_contains_result(ALIAS_VAR_0,parallel_composition(X,Y,max_aggregator),ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% mod_contains_result_alias_3
mod_contains_result(ALIAS_VAR_0,smc(X),ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- mod_contains_result(ALIAS_VAR_0,iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X))),ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% mod_contains_result_alias_4
mod_contains_result(ALIAS_VAR_0,elector(X),ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- mod_contains_result(ALIAS_VAR_0,sequential_composition(X,elect_module),ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = Sequential_Majority_Comparison.thy
% Sequential_Majority_Comparison.smc_monotone
monotonicity(smc(X)) :- linear_order(X).

% = ASSUMPTION
% monotonicity_alias_0
monotonicity(iter(X)) :- monotonicity(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% monotonicity_alias_1
monotonicity(iterelect(X)) :- monotonicity(elector(iter(X))).

% = ASSUMPTION
% monotonicity_alias_2
monotonicity(maximum_parallel_composition(X,Y)) :- monotonicity(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% monotonicity_alias_3
monotonicity(smc(X)) :- monotonicity(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% monotonicity_alias_4
monotonicity(elector(X)) :- monotonicity(sequential_composition(X,elect_module)).

% = Monotonicity_Rules.thy
% Monotonicity_Rules.seq_comp_mono
monotonicity(sequential_composition(M,N)) :- defer_lift_invariance(M),non_electing(M),defers(1,M),electing(N).

% = Result_Rules.thy
% Result_Rules.electing_imp_non_blocking
non_blocking(M) :- electing(M).

% = ASSUMPTION
% non_blocking_alias_0
non_blocking(iter(X)) :- non_blocking(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% non_blocking_alias_1
non_blocking(iterelect(X)) :- non_blocking(elector(iter(X))).

% = ASSUMPTION
% non_blocking_alias_2
non_blocking(maximum_parallel_composition(X,Y)) :- non_blocking(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% non_blocking_alias_3
non_blocking(smc(X)) :- non_blocking(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% non_blocking_alias_4
non_blocking(elector(X)) :- non_blocking(sequential_composition(X,elect_module)).

% = Result_Rules.thy
% Result_Rules.seq_comp_presv_non_blocking
non_blocking(sequential_composition(M,N)) :- non_blocking(M),non_blocking(N).

% = Result_Facts.thy
% Result_Facts.def_mod_non_electing
non_electing(defer_module).

% = Result_Rules.thy
% Result_Rules.loop_comp_presv_non_electing
non_electing(loop_composition(M,_)) :- non_electing(M).

% = Result_Facts.thy
% Result_Facts.drop_mod_non_electing
non_electing(drop_module(_,R)) :- linear_order(R).

% = Result_Facts.thy
% Result_Facts.less_elim_non_electing
non_electing(less_eliminator(_,_)) :- finite_profile(_,_).

% = Result_Facts.thy
% Result_Facts.less_avg_elim_non_electing
non_electing(less_average_eliminator(_)) :- finite_profile(_,_).

% = Result_Facts.thy
% Result_Facts.leq_elim_non_electing
non_electing(leq_eliminator(_,_)) :- finite_profile(_,_).

% = Result_Facts.thy
% Result_Facts.min_elim_non_electing
non_electing(min_eliminator(_)) :- finite_profile(_,_).

% = Result_Facts.thy
% Result_Facts.elim_mod_non_electing
non_electing(elimination_module(_,_,_)) :- finite_profile(_,_).

% = Result_Facts.thy
% Result_Facts.rev_comp_non_electing
non_electing(revision_composition(M)) :- electoral_module(M).

% = Result_Facts.thy
% Result_Facts.pass_mod_non_electing
non_electing(pass_module(_,R)) :- linear_order(R).

% = Result_Facts.thy
% Result_Facts.max_elim_non_electing
non_electing(max_eliminator(_)) :- finite_profile(_,_).

% = Result_Facts.thy
% Result_Facts.leq_avg_elim_non_electing
non_electing(leq_average_eliminator(_)) :- finite_profile(_,_).

% = ASSUMPTION
% non_electing_alias_0
non_electing(iter(X)) :- non_electing(loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% non_electing_alias_1
non_electing(iterelect(X)) :- non_electing(elector(iter(X))).

% = ASSUMPTION
% non_electing_alias_2
non_electing(maximum_parallel_composition(X,Y)) :- non_electing(parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% non_electing_alias_3
non_electing(smc(X)) :- non_electing(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% non_electing_alias_4
non_electing(elector(X)) :- non_electing(sequential_composition(X,elect_module)).

% = Result_Rules.thy
% Result_Rules.seq_comp_presv_non_electing
non_electing(sequential_composition(M,N)) :- non_electing(M),non_electing(N).

% = Result_Rules.thy
% Result_Rules.conserv_max_agg_presv_non_electing
non_electing(maximum_parallel_composition(M,N)) :- non_electing(M),non_electing(N).

% = Result_Rules.thy
% Result_Rules.conserv_agg_presv_non_electing
non_electing(parallel_composition(M,N,A)) :- non_electing(M),non_electing(N),agg_conservative(A).

% = ASSUMPTION
% prof_contains_result_alias_0
prof_contains_result(iter(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_contains_result(loop_composition(X,defer_equal_condition(1)),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_contains_result_alias_1
prof_contains_result(iterelect(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_contains_result(elector(iter(X)),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_contains_result_alias_2
prof_contains_result(maximum_parallel_composition(X,Y),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_contains_result(parallel_composition(X,Y,max_aggregator),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_contains_result_alias_3
prof_contains_result(smc(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_contains_result(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X))),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_contains_result_alias_4
prof_contains_result(elector(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_contains_result(sequential_composition(X,elect_module),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_geq_result_alias_0
prof_geq_result(iter(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_geq_result(loop_composition(X,defer_equal_condition(1)),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_geq_result_alias_1
prof_geq_result(iterelect(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_geq_result(elector(iter(X)),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_geq_result_alias_2
prof_geq_result(maximum_parallel_composition(X,Y),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_geq_result(parallel_composition(X,Y,max_aggregator),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_geq_result_alias_3
prof_geq_result(smc(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_geq_result(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X))),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_geq_result_alias_4
prof_geq_result(elector(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_geq_result(sequential_composition(X,elect_module),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_leq_result_alias_0
prof_leq_result(iter(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_leq_result(loop_composition(X,defer_equal_condition(1)),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_leq_result_alias_1
prof_leq_result(iterelect(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_leq_result(elector(iter(X)),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_leq_result_alias_2
prof_leq_result(maximum_parallel_composition(X,Y),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_leq_result(parallel_composition(X,Y,max_aggregator),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_leq_result_alias_3
prof_leq_result(smc(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_leq_result(iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X))),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% prof_leq_result_alias_4
prof_leq_result(elector(X),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4) :- prof_leq_result(sequential_composition(X,elect_module),ALIAS_VAR_1,ALIAS_VAR_2,ALIAS_VAR_3,ALIAS_VAR_4).

% = ASSUMPTION
% profile_intro
profile(_,_).

% = Preference_Relation.thy
% Preference_Relation.connex_imp_refl
refl_on(A,R) :- connex(A,R).

% = Result_Facts.thy
% Result_Facts.drop_two_mod_rej_two
rejects(2,drop_module(2,R)) :- linear_order(R).

% = Result_Facts.thy
% Result_Facts.drop_zero_mod_rej_zero
rejects(0,drop_module(0,R)) :- linear_order(R).

% = ASSUMPTION
% rejects_alias_0
rejects(ALIAS_VAR_0,iter(X)) :- rejects(ALIAS_VAR_0,loop_composition(X,defer_equal_condition(1))).

% = ASSUMPTION
% rejects_alias_1
rejects(ALIAS_VAR_0,iterelect(X)) :- rejects(ALIAS_VAR_0,elector(iter(X))).

% = ASSUMPTION
% rejects_alias_2
rejects(ALIAS_VAR_0,maximum_parallel_composition(X,Y)) :- rejects(ALIAS_VAR_0,parallel_composition(X,Y,max_aggregator)).

% = ASSUMPTION
% rejects_alias_3
rejects(ALIAS_VAR_0,smc(X)) :- rejects(ALIAS_VAR_0,iterelect(maximum_parallel_composition(sequential_composition(pass_module(2,X),sequential_composition(revision_composition(plurality),pass_module(1,X))),drop_module(2,X)))).

% = ASSUMPTION
% rejects_alias_4
rejects(ALIAS_VAR_0,elector(X)) :- rejects(ALIAS_VAR_0,sequential_composition(X,elect_module)).

% = Sequential_Composition.thy
% Sequential_Composition.seq_comp_presv_alts
set_equals_partition(A,sequential_composition(M,N,A,P)) :- electoral_module(M),electoral_module(N),finite_profile(A,P).

% = ASSUMPTION
% trans_intro
trans(_).

% = Preference_Relation.thy
% Preference_Relation.lin_imp_trans
trans(R) :- linear_order_on(_,R).

% = ASSUMPTION
% wins_intro
wins(_,_,_).

