package com.fr2501.virage.prolog;

public enum ParserState {
	STARTING,
	FRAMEWORK_COMPONENT,
	COMPOSITION_TYPE,
	COMPOSABLE_MODULE,
	COMPOSITIONAL_STRUCTURE,
	PROPERTY,
	COMPOSITION_RULE,
	FINALIZED;
}
